### ISSUE TITLE
Better failed login attempt message

### ISSUE THREAD

**Issue by joelhanneman** [TPM-Repos/ModifiedCorporateTheme#32] opened 2024-05-23 12:31 UTC
Shows something better than "There has been an issue".  Can't imagine this is helpful to end users.
"We could not log you in"
"We did not recognize those credentials"
etc..

**Comment by jccaswell** [comment] 2024-05-23 14:17
This is a duplicate of issue #13

**Closed by jccaswell** 2024-05-23 14:17 UTC
Labels: duplicate, enhancement
